import { v4 as uuidv4 } from "uuid";

const artworks = [
  {
    id: uuidv4(),
    title: "A Vision in Color",
    artist: "Liora Senn",
    image: "/images/a_vision_in_color.webp",
    description:
      "Bold brushstrokes and rich hues of purple, blue, and red bring this abstract masterpiece to life. A striking blend of movement and emotion, this piece captures energy and depth in every layer.",
    averageRating: 4,
    type: "portrait",
    sizes: [
      { dimensions: "40 x 55 cm", price: 350 },
      { dimensions: "50 x 70 cm", price: 450 },
      { dimensions: "60 x 85 cm", price: 550 },
      { dimensions: "70 x 100 cm", price: 650 },
      { dimensions: "85 x 120 cm", price: 750 },
      { dimensions: "100 x 140 cm", price: 850 },
    ],
    reviews: [
      {
        name: "Sarah M.",
        date: "January 10, 2025",
        rating: 5,
        text: "Absolutely stunning! The colors are vibrant, and the details are even more breathtaking in person.",
      },
      {
        name: "John D.",
        date: "February 5, 2025",
        rating: 4,
        text: "Beautiful artwork, but the frame was slightly scratched upon arrival. Still a great piece!",
      },
    ],
  },
  {
    id: uuidv4(),
    title: "The Spirit of Freedom",
    artist: "Elias Varnen",
    image: "/images/the_spirit_of_freedom.webp",
    description:
      "Vivid colors and flowing forms embody the untamed essence of movement. This artwork captures the raw energy and boundless freedom of a soul unrestrained.",
    averageRating: 5,
    type: "landscape",
    sizes: [
      { dimensions: "55 x 40 cm", price: 300 },
      { dimensions: "70 x 50 cm", price: 400 },
      { dimensions: "85 x 60 cm", price: 500 },
      { dimensions: "100 x 70 cm", price: 600 },
      { dimensions: "120 x 85 cm", price: 700 },
      { dimensions: "140 x 100 cm", price: 800 },
    ],
    reviews: [
      {
        name: "Emily R.",
        date: "March 8, 2025",
        rating: 5,
        text: "This piece brought so much life into my living room. Highly recommended!",
      },
      {
        name: "Liam K.",
        date: "April 1, 2025",
        rating: 5,
        text: "Even more beautiful in person than online. Great quality!",
      },
    ],
  },
  {
    id: uuidv4(),
    title: "Whispers of the Bloom",
    artist: "Camille Verdain",
    image: "/images/whispers_of_the_bloom.webp",
    description:
      "An impressionist vision of a sunlit poppy field, where vivid colors and dynamic brushstrokes capture the beauty of nature in motion.",
    averageRating: 5,
    type: "landscape",
    sizes: [
      { dimensions: "60 x 45 cm", price: 250 },
      { dimensions: "75 x 55 cm", price: 350 },
      { dimensions: "90 x 65 cm", price: 450 },
      { dimensions: "110 x 80 cm", price: 550 },
      { dimensions: "130 x 95 cm", price: 650 },
      { dimensions: "150 x 110 cm", price: 750 },
    ],
    reviews: [
      {
        name: "Olivia P.",
        date: "June 22, 2025",
        rating: 5,
        text: "Absolutely love this piece! It fits perfectly in my dining room.",
      },
    ],
  },
  {
    id: uuidv4(),
    title: "Guardian of Healing",
    artist: "Lucien Moreau",
    image: "/images/guardian_of_healing.webp",
    description:
      "A quiet devotion unfolds in flowing color, where light and movement intertwine with the weight of knowledge and the urgency of compassion. Each brushstroke lingers, a testament to hands that heal and time that passes.",
    averageRating: 4,
    type: "square",
    sizes: [
      { dimensions: "55 x 40 cm", price: 300 },
      { dimensions: "70 x 50 cm", price: 400 },
      { dimensions: "85 x 60 cm", price: 500 },
      { dimensions: "100 x 70 cm", price: 600 },
      { dimensions: "120 x 85 cm", price: 700 },
      { dimensions: "140 x 100 cm", price: 800 },
    ],
    reviews: [
      {
        name: "Noah W.",
        date: "May 15, 2025",
        rating: 4,
        text: "A great addition to my office, but shipping took longer than expected.",
      },
    ],
  },
  {
    id: uuidv4(),
    title: "Sunflowers at Dusk",
    artist: "Elias Varnen",
    image: "/images/sunflowers_at_dusk.webp",
    description:
      "An impressionist vision of a sunflower field at dusk, where vibrant yellows and warm golden hues dance across the canvas, brought to life by dynamic brushstrokes that capture the fleeting beauty of twilight.",
    averageRating: 5,
    type: "landscape",
    sizes: [
      { dimensions: "58 x 42 cm", price: 200 },
      { dimensions: "72 x 52 cm", price: 300 },
      { dimensions: "88 x 65 cm", price: 400 },
      { dimensions: "105 x 75 cm", price: 500 },
      { dimensions: "125 x 90 cm", price: 600 },
      { dimensions: "145 x 105 cm", price: 700 },
    ],
    reviews: [
      {
        name: "James C.",
        date: "July 30, 2025",
        rating: 5,
        text: "The details in this painting are incredible. Looks even better in natural light!",
      },
      {
        name: "Sophia L.",
        date: "August 12, 2025",
        rating: 5,
        text: "The colors are so rich and deep. Perfect for my bedroom!",
      },
    ],
  },
  {
    id: uuidv4(),
    title: "Whispering Canopy",
    artist: "Marc Monnet",
    image: "/images/whispering_canopy.webp",
    description:
      "A mesmerizing woodland scene where sunlight filters through dense foliage, casting an ethereal glow on the forest path. Rich in greens and deep blues, this painting evokes serenity and mystery, drawing viewers into nature’s embrace.",
    averageRating: 4.5,
    type: "square",
    sizes: [
      { dimensions: "40 x 55 cm", price: 375 },
      { dimensions: "50 x 70 cm", price: 475 },
      { dimensions: "60 x 85 cm", price: 575 },
      { dimensions: "70 x 100 cm", price: 675 },
      { dimensions: "85 x 120 cm", price: 775 },
      { dimensions: "100 x 140 cm", price: 875 },
    ],
    reviews: [],
  },
  {
    id: uuidv4(),
    title: "Golden Metropolis",
    artist: "Elijah Carter",
    image: "/images/golden_metropolis.webp",
    description:
      "A breathtaking cityscape bathed in golden hues as the sunlight reflects off towering skyscrapers. Thick, textured brushstrokes create a dynamic sense of movement in this bustling urban scene, capturing the energy and vibrancy of city life.",
    averageRating: 4.7,
    type: "portrait",
    sizes: [
      { dimensions: "40 x 55 cm", price: 400 },
      { dimensions: "50 x 70 cm", price: 500 },
      { dimensions: "60 x 85 cm", price: 600 },
      { dimensions: "70 x 100 cm", price: 700 },
      { dimensions: "85 x 120 cm", price: 800 },
      { dimensions: "100 x 140 cm", price: 900 },
    ],
    reviews: [],
  },
  {
    id: uuidv4(),
    title: "Twilight Reflections",
    artist: "Nathaniel Harper",
    image: "/images/twilight_reflections.webp",
    description:
      "An enchanting city skyline illuminated by the warm glow of twilight. The vibrant mix of purples, oranges, and blues brings depth and emotion to this mesmerizing urban scene, where reflections dance on the shimmering water below.",
    averageRating: 4.8,
    type: "square",
    sizes: [
      { dimensions: "40 x 55 cm", price: 420 },
      { dimensions: "50 x 70 cm", price: 520 },
      { dimensions: "60 x 85 cm", price: 620 },
      { dimensions: "70 x 100 cm", price: 720 },
      { dimensions: "85 x 120 cm", price: 820 },
      { dimensions: "100 x 140 cm", price: 920 },
    ],
    reviews: [],
  },
  {
    id: uuidv4(),
    title: "Tempest’s Dance",
    artist: "Isla Davenport",
    image: "/images/tempest_dance.webp",
    description:
      "Powerful waves crash and swirl in this mesmerizing seascape, capturing the raw energy and movement of the ocean. The rich blues, greens, and whites blend seamlessly, creating a sense of both chaos and harmony in this breathtaking painting.",
    averageRating: 4.9,
    type: "landscape",
    sizes: [
      { dimensions: "40 x 55 cm", price: 430 },
      { dimensions: "50 x 70 cm", price: 530 },
      { dimensions: "60 x 85 cm", price: 630 },
      { dimensions: "70 x 100 cm", price: 730 },
      { dimensions: "85 x 120 cm", price: 830 },
      { dimensions: "100 x 140 cm", price: 930 },
    ],
    reviews: [],
  },
  {
    id: uuidv4(),
    title: "Meadow Serenity",
    artist: "Eleanor Marchand",
    image: "/images/meadow_serenity.webp",
    description:
      "A tranquil river winds through a lush, colorful meadow, bathed in the golden glow of a serene afternoon. Soft brushstrokes and a rich palette of greens, yellows, and wildflower hues bring this peaceful landscape to life, evoking a sense of harmony and calm.",
    averageRating: 4.8,
    type: "landscape",
    sizes: [
      { dimensions: "40 x 55 cm", price: 410 },
      { dimensions: "50 x 70 cm", price: 510 },
      { dimensions: "60 x 85 cm", price: 610 },
      { dimensions: "70 x 100 cm", price: 710 },
      { dimensions: "85 x 120 cm", price: 810 },
      { dimensions: "100 x 140 cm", price: 910 },
    ],
    reviews: [],
  },
  {
    id: uuidv4(),
    title: "Majestic Peaks",
    artist: "Julian Ashford",
    image: "/images/majestic_peaks.webp",
    description:
      "A breathtaking mountain range bathed in the golden hues of dawn. Snow-capped peaks rise dramatically above a tranquil lake, as mist gently rolls over the valleys. This stunning landscape captures the grandeur and serenity of nature at its finest.",
    averageRating: 4.9,
    type: "square",
    sizes: [
      { dimensions: "40 x 55 cm", price: 450 },
      { dimensions: "50 x 70 cm", price: 550 },
      { dimensions: "60 x 85 cm", price: 650 },
      { dimensions: "70 x 100 cm", price: 750 },
      { dimensions: "85 x 120 cm", price: 850 },
      { dimensions: "100 x 140 cm", price: 950 },
    ],
    reviews: [],
  },
  {
    id: uuidv4(),
    title: "Whispering Falls",
    artist: "Elias Varnen",
    image: "/images/whispering_falls.webp",
    description:
      "An impressionist masterpiece capturing the ethereal beauty of a cascading waterfall surrounded by lush greenery. The vibrant brushstrokes and dreamy colors bring the scene to life, evoking a sense of movement and tranquility.",
    averageRating: 4.9,
    type: "landscape",
    sizes: [
      { dimensions: "55 x 40 cm", price: 320 },
      { dimensions: "70 x 50 cm", price: 430 },
      { dimensions: "85 x 60 cm", price: 540 },
      { dimensions: "100 x 70 cm", price: 650 },
      { dimensions: "120 x 85 cm", price: 760 },
      { dimensions: "140 x 100 cm", price: 870 },
    ],
    reviews: [
      {
        name: "Olivia S.",
        date: "May 2, 2025",
        rating: 5,
        text: "The brushstrokes and colors give this piece so much life. It feels like standing in front of a real waterfall!",
      },
      {
        name: "James L.",
        date: "May 5, 2025",
        rating: 4,
        text: "Absolutely stunning work. The impressionist style makes it feel timeless and full of energy!",
      },
    ],
  },
  {
    id: uuidv4(),
    title: "Golden Horizon",
    artist: "Elias Varnen",
    image: "/images/golden_horizon.webp",
    description:
      "Rolling green hills bathed in golden sunlight stretch into the horizon. The textured brushstrokes capture the wind dancing through the grass, while the soft pastel sky adds depth and warmth. A truly serene and timeless landscape.",
    averageRating: 4.8,
    type: "landscape",
    sizes: [
      { dimensions: "55 x 40 cm", price: 320 },
      { dimensions: "70 x 50 cm", price: 430 },
      { dimensions: "85 x 60 cm", price: 540 },
      { dimensions: "100 x 70 cm", price: 650 },
      { dimensions: "120 x 85 cm", price: 760 },
      { dimensions: "140 x 100 cm", price: 870 },
    ],
    reviews: [
      {
        name: "Isabella T.",
        date: "May 10, 2025",
        rating: 5,
        text: "This artwork fills my space with warmth and tranquility. The rolling hills feel alive!",
      },
      {
        name: "Ethan W.",
        date: "May 12, 2025",
        rating: 4,
        text: "The texture and colors are absolutely mesmerizing. Perfect for a nature lover!",
      },
    ],
  },
  {
    id: uuidv4(),
    title: "The Cozy Haven",
    artist: "Livia Marceau",
    image: "/images/the_cozy_haven.webp",
    description:
      "Nestled among vibrant wildflowers, this picturesque countryside cottage exudes warmth and tranquility. Golden sunlight bathes the stone walls, while a winding path leads to the inviting front door. The impressionist brushstrokes bring life to the trees and sky, making this an enchanting escape into nature.",
    averageRating: 4.9,
    type: "landscape",
    sizes: [
      { dimensions: "55 x 40 cm", price: 330 },
      { dimensions: "70 x 50 cm", price: 440 },
      { dimensions: "85 x 60 cm", price: 550 },
      { dimensions: "100 x 70 cm", price: 660 },
      { dimensions: "120 x 85 cm", price: 770 },
      { dimensions: "140 x 100 cm", price: 880 },
    ],
    reviews: [
      {
        name: "Amelia V.",
        date: "May 18, 2025",
        rating: 5,
        text: "I feel like I could step into this painting and be transported to a peaceful countryside retreat. Absolutely stunning!",
      },
      {
        name: "Benjamin S.",
        date: "May 20, 2025",
        rating: 4,
        text: "The colors and light in this piece are magical. It brings so much warmth to my home.",
      },
      {
        name: "Charlotte L.",
        date: "May 21, 2025",
        rating: 5,
        text: "This artwork captures everything I love about the countryside—charm, peace, and natural beauty.",
      },
    ],
  },
  {
    id: uuidv4(),
    title: "Tempest Unleashed",
    artist: "Victor Ardent",
    image: "/images/tempest_unleashed.webp",
    description:
      "Towering waves crash against jagged cliffs as storm clouds swirl overhead. A haunting glow filters through the darkness, illuminating the chaotic sea in this breathtaking impressionist masterpiece. The powerful brushstrokes and deep contrasts capture the raw energy and beauty of nature’s untamed force.",
    averageRating: 4.9,
    type: "landscape",
    sizes: [
      { dimensions: "55 x 40 cm", price: 340 },
      { dimensions: "70 x 50 cm", price: 450 },
      { dimensions: "85 x 60 cm", price: 560 },
      { dimensions: "100 x 70 cm", price: 670 },
      { dimensions: "120 x 85 cm", price: 780 },
      { dimensions: "140 x 100 cm", price: 890 },
    ],
    reviews: [
      {
        name: "Nathan R.",
        date: "May 25, 2025",
        rating: 5,
        text: "The movement in this piece is incredible. It feels like the waves could crash right out of the painting!",
      },
      {
        name: "Isla P.",
        date: "May 27, 2025",
        rating: 5,
        text: "The stormy atmosphere gives it such an intense presence. A stunning addition to my collection!",
      },
      {
        name: "Oliver H.",
        date: "May 28, 2025",
        rating: 5,
        text: "The energy in this artwork is captivating. Every time I look at it, I notice new details.",
      },
      {
        name: "Sophia T.",
        date: "May 29, 2025",
        rating: 4,
        text: "The mix of dark tones with the golden light is so striking. Truly a masterpiece!",
      },
    ],
  },
  {
    id: uuidv4(),
    title: "City Lights",
    artist: "Marcello Fontaine",
    image: "/images/city_lights.webp",
    description:
      "A bustling city street at dusk comes alive with shimmering reflections of neon lights on the wet pavement. Silhouetted figures move through the glow of streetlamps, their forms captured in expressive, impressionist brushstrokes. The atmosphere is rich with movement, color, and the timeless beauty of urban life.",
    averageRating: 4.9,
    type: "landscape",
    sizes: [
      { dimensions: "55 x 40 cm", price: 350 },
      { dimensions: "70 x 50 cm", price: 460 },
      { dimensions: "85 x 60 cm", price: 570 },
      { dimensions: "100 x 70 cm", price: 680 },
      { dimensions: "120 x 85 cm", price: 790 },
      { dimensions: "140 x 100 cm", price: 900 },
    ],
    reviews: [
      {
        name: "Daniel J.",
        date: "June 5, 2025",
        rating: 5,
        text: "This piece captures the magic of the city at night so beautifully. The reflections and colors are mesmerizing!",
      },
      {
        name: "Emma K.",
        date: "June 7, 2025",
        rating: 4,
        text: "I love how the movement of people and lights feels so dynamic. A wonderful piece for any urban art lover!",
      },
      {
        name: "Lucas P.",
        date: "June 9, 2025",
        rating: 5,
        text: "This painting brings a lively energy to my living space. It feels like stepping into a city full of life and stories.",
      },
      {
        name: "Sophia W.",
        date: "June 10, 2025",
        rating: 4,
        text: "The atmosphere in this artwork is incredible! The way the lights reflect off the wet pavement is stunning.",
      },
    ],
  },
  {
    id: uuidv4(),
    title: "Autumn Serenity",
    artist: "Elara Duvall",
    image: "/images/autumn_serenity.webp",
    description:
      "Golden leaves blanket the ground as a soft autumn breeze rustles through the trees. A winding path leads through the peaceful park, where warm lamplights glow softly near a reflective pond. Expressive brushstrokes bring a dreamy, nostalgic atmosphere to this stunning impressionist scene.",
    averageRating: 5,
    type: "landscape",
    sizes: [
      { dimensions: "55 x 40 cm", price: 340 },
      { dimensions: "70 x 50 cm", price: 450 },
      { dimensions: "85 x 60 cm", price: 560 },
      { dimensions: "100 x 70 cm", price: 670 },
      { dimensions: "120 x 85 cm", price: 780 },
      { dimensions: "140 x 100 cm", price: 890 },
    ],
    reviews: [
      {
        name: "Henry B.",
        date: "June 15, 2025",
        rating: 5,
        text: "This painting reminds me of peaceful autumn walks. The colors are so rich and warm!",
      },
      {
        name: "Olivia M.",
        date: "June 17, 2025",
        rating: 5,
        text: "Absolutely stunning! The reflections and textures make this piece feel so alive.",
      },
      {
        name: "Ethan L.",
        date: "June 18, 2025",
        rating: 5,
        text: "I can almost feel the crisp autumn air. The details in this painting are breathtaking.",
      },
      {
        name: "Sophia C.",
        date: "June 19, 2025",
        rating: 4,
        text: "A wonderful addition to my collection. It brings such a calming presence to my home.",
      },
      {
        name: "Noah W.",
        date: "June 20, 2025",
        rating: 5,
        text: "The glow of the lamplights and the golden leaves create such a cozy feeling. I love it!",
      },
    ],
  },
  {
    id: uuidv4(),
    title: "Urban Heights",
    artist: "Sebastian Moreau",
    image: "/images/urban_heights.webp",
    description:
      "Towering skyscrapers rise into the evening sky, their glass facades glowing with the warm hues of the setting sun. Expressive brushstrokes capture the shimmering reflections and the energy of the bustling city below. A breathtaking vertical composition that evokes the grandeur of modern architecture.",
    averageRating: 5,
    type: "portrait",
    sizes: [
      { dimensions: "40 x 55 cm", price: 360 },
      { dimensions: "50 x 70 cm", price: 470 },
      { dimensions: "60 x 85 cm", price: 580 },
      { dimensions: "70 x 100 cm", price: 690 },
      { dimensions: "85 x 120 cm", price: 800 },
      { dimensions: "100 x 140 cm", price: 910 },
    ],
    reviews: [
      {
        name: "Michael D.",
        date: "June 25, 2025",
        rating: 5,
        text: "This piece captures the beauty and energy of the city skyline perfectly! The colors are stunning.",
      },
      {
        name: "Emily R.",
        date: "June 27, 2025",
        rating: 5,
        text: "Absolutely mesmerizing. The sense of height and movement in this painting is incredible.",
      },
      {
        name: "Jacob H.",
        date: "June 28, 2025",
        rating: 5,
        text: "A masterpiece! It brings such a modern and elegant feel to my office.",
      },
      {
        name: "Sophia W.",
        date: "June 29, 2025",
        rating: 4,
        text: "Love the reflections on the buildings. I wish the sky had a bit more contrast, but still an amazing piece!",
      },
      {
        name: "Olivia T.",
        date: "June 30, 2025",
        rating: 5,
        text: "The way the city lights interact with the sunset is just breathtaking. It’s my favorite art piece now!",
      },
    ],
  },
  {
    id: uuidv4(),
    title: "Reflections of Stillness",
    artist: "Isabelle Laurent",
    image: "/images/reflections_of_stillness.webp",
    description:
      "A tranquil lake mirrors the soft hues of the sky as golden sunlight filters through the trees. Gentle ripples dance across the water, adding depth and movement to this serene scene. Expressive brushstrokes bring warmth and harmony, making this impressionist masterpiece a window into nature’s peaceful embrace.",
    averageRating: 5,
    type: "landscape",
    sizes: [
      { dimensions: "55 x 40 cm", price: 350 },
      { dimensions: "70 x 50 cm", price: 460 },
      { dimensions: "85 x 60 cm", price: 570 },
      { dimensions: "100 x 70 cm", price: 680 },
      { dimensions: "120 x 85 cm", price: 790 },
      { dimensions: "140 x 100 cm", price: 900 },
    ],
    reviews: [
      {
        name: "Charlotte M.",
        date: "July 5, 2025",
        rating: 5,
        text: "The reflections on the lake are mesmerizing. It brings such a calming presence to my space!",
      },
      {
        name: "Daniel S.",
        date: "July 7, 2025",
        rating: 5,
        text: "This painting makes me feel like I’m standing by the water at sunset. Absolutely stunning.",
      },
      {
        name: "Emma R.",
        date: "July 8, 2025",
        rating: 4,
        text: "A beautiful piece! I wish there was a little more contrast in the sky, but the colors are lovely.",
      },
      {
        name: "Lucas B.",
        date: "July 9, 2025",
        rating: 5,
        text: "This painting captures the essence of serenity. The brushstrokes add such a dreamy touch!",
      },
      {
        name: "Sophia L.",
        date: "July 10, 2025",
        rating: 5,
        text: "A true masterpiece! The play of light on the water is so enchanting.",
      },
    ],
  },
  {
    id: uuidv4(),
    title: "Emerald Wilderness",
    artist: "Lucien Navarro",
    image: "/images/emerald_wilderness.webp",
    description:
      "Dense and untamed, this vibrant jungle scene captures the raw beauty of nature. Sunlight pierces through the canopy, illuminating the rich greenery and bursts of exotic flowers. Expressive impressionist brushstrokes bring movement to the foliage, creating an immersive escape into the heart of the wild.",
    averageRating: 5,
    type: "square",
    sizes: [
      { dimensions: "40 x 40 cm", price: 340 },
      { dimensions: "50 x 50 cm", price: 450 },
      { dimensions: "60 x 60 cm", price: 560 },
      { dimensions: "70 x 70 cm", price: 670 },
      { dimensions: "85 x 85 cm", price: 780 },
      { dimensions: "100 x 100 cm", price: 890 },
    ],
    reviews: [
      {
        name: "Ethan R.",
        date: "July 15, 2025",
        rating: 5,
        text: "The lush greenery feels so alive! This painting adds such a refreshing vibe to my home.",
      },
      {
        name: "Amelia T.",
        date: "July 17, 2025",
        rating: 5,
        text: "Absolutely stunning. The light filtering through the trees is captured beautifully.",
      },
      {
        name: "James L.",
        date: "July 18, 2025",
        rating: 4,
        text: "Love the wild feel of this piece. I wish there were even more vibrant flowers for contrast.",
      },
      {
        name: "Sophia N.",
        date: "July 19, 2025",
        rating: 5,
        text: "A gorgeous representation of nature’s untouched beauty. The brushstrokes are mesmerizing!",
      },
      {
        name: "Noah P.",
        date: "July 20, 2025",
        rating: 5,
        text: "It feels like stepping into a jungle. The textures and colors are just perfect.",
      },
    ],
  },
  {
    id: uuidv4(),
    title: "Fragmented Identity",
    artist: "Nico Vargas",
    image: "/images/fragmented_identity.webp",
    description:
      "A bold and expressive cubist portrait, deconstructing the human form into dynamic geometric shapes and overlapping perspectives. Vivid contrasts of color and fragmented planes create a striking sense of depth and emotion, inviting the viewer to interpret multiple facets of identity.",
    averageRating: 5,
    type: "portrait",
    sizes: [
      { dimensions: "40 x 55 cm", price: 370 },
      { dimensions: "50 x 70 cm", price: 480 },
      { dimensions: "60 x 85 cm", price: 590 },
      { dimensions: "70 x 100 cm", price: 700 },
      { dimensions: "85 x 120 cm", price: 810 },
      { dimensions: "100 x 140 cm", price: 920 },
    ],
    reviews: [
      {
        name: "Liam D.",
        date: "July 25, 2025",
        rating: 5,
        text: "The cubist style is mesmerizing! The fragmented shapes give such a unique personality to this piece.",
      },
      {
        name: "Sophia M.",
        date: "July 27, 2025",
        rating: 5,
        text: "A striking and thought-provoking portrait. The bold colors and angles make it feel alive!",
      },
      {
        name: "Ethan K.",
        date: "July 28, 2025",
        rating: 4,
        text: "I love the abstraction, though I wish the colors were slightly softer. Still a fantastic piece!",
      },
      {
        name: "Olivia P.",
        date: "July 29, 2025",
        rating: 5,
        text: "Absolutely stunning! The depth and complexity of the portrait keep me coming back to see more details.",
      },
      {
        name: "Noah J.",
        date: "July 30, 2025",
        rating: 5,
        text: "This is a conversation starter for sure! A masterpiece of modern cubism.",
      },
    ],
  },
  {
    id: uuidv4(),
    title: "Defender of the Nation",
    artist: "Viktor Sokolov",
    image: "/images/defender_of_the_nation.webp",
    description:
      "A striking impressionist-style propaganda poster featuring a heroic soldier standing with unwavering resolve. Expressive brushstrokes bring life to the determined gaze and strong posture, while the patriotic background evokes unity and strength. A bold and inspiring piece that merges history with artistic expression.",
    averageRating: 5,
    type: "portrait",
    sizes: [
      { dimensions: "40 x 55 cm", price: 380 },
      { dimensions: "50 x 70 cm", price: 490 },
      { dimensions: "60 x 85 cm", price: 600 },
      { dimensions: "70 x 100 cm", price: 710 },
      { dimensions: "85 x 120 cm", price: 820 },
      { dimensions: "100 x 140 cm", price: 930 },
    ],
    reviews: [
      {
        name: "Alexei M.",
        date: "August 5, 2025",
        rating: 5,
        text: "This piece captures the strength and determination of a true defender. The brushwork adds so much depth!",
      },
      {
        name: "Elena V.",
        date: "August 7, 2025",
        rating: 5,
        text: "A powerful and emotional artwork. The colors and expression make it a true masterpiece!",
      },
      {
        name: "Mark T.",
        date: "August 8, 2025",
        rating: 4,
        text: "I love the impressionist take on a propaganda poster. The textures are fantastic!",
      },
      {
        name: "Sophie R.",
        date: "August 9, 2025",
        rating: 5,
        text: "This artwork feels historic and modern at the same time. The energy is amazing!",
      },
      {
        name: "Nikolai P.",
        date: "August 10, 2025",
        rating: 5,
        text: "A bold and inspiring piece. It would make a great centerpiece in any collection!",
      },
    ],
  },
  {
    id: uuidv4(),
    title: "Monolithic Silence",
    artist: "Adrian Kovacs",
    image: "/images/monolithic_silence.webp",
    description:
      "Towering brutalist structures rise against a moody sky, their geometric forms casting deep shadows over the raw concrete landscape. Expressive brushstrokes soften the rigid geometry, blending light and shadow to create an atmospheric dreamlike effect. A powerful tribute to the beauty of brutalism through impressionist abstraction.",
    averageRating: 5,
    type: "landscape",
    sizes: [
      { dimensions: "55 x 40 cm", price: 360 },
      { dimensions: "70 x 50 cm", price: 470 },
      { dimensions: "85 x 60 cm", price: 580 },
      { dimensions: "100 x 70 cm", price: 690 },
      { dimensions: "120 x 85 cm", price: 800 },
      { dimensions: "140 x 100 cm", price: 910 },
    ],
    reviews: [
      {
        name: "Liam H.",
        date: "August 25, 2025",
        rating: 5,
        text: "The depth and weight of this piece are incredible. It captures the essence of brutalism perfectly!",
      },
      {
        name: "Isabelle F.",
        date: "August 27, 2025",
        rating: 5,
        text: "A hauntingly beautiful depiction of brutalist architecture. The interplay of light and shadow is mesmerizing.",
      },
      {
        name: "Nathan R.",
        date: "August 28, 2025",
        rating: 4,
        text: "I love the composition, but I wish there were a bit more contrast in the concrete textures.",
      },
      {
        name: "Sophia W.",
        date: "August 29, 2025",
        rating: 5,
        text: "The atmosphere in this painting is intense and thought-provoking. A must-have for modern architecture lovers!",
      },
      {
        name: "Oliver T.",
        date: "August 30, 2025",
        rating: 5,
        text: "It feels like stepping into a dystopian yet fascinating world. The brushstrokes add so much personality to the concrete.",
      },
    ],
  },
  {
    id: uuidv4(),
    title: "Majestic Cliffs",
    artist: "William Ashford",
    image: "/images/majestic_cliffs.webp",
    description:
      "The towering white chalk cliffs of Dover stand proudly against the deep blue sea, their rugged textures brought to life with expressive impressionist brushstrokes. Sunlight filters through a soft, cloudy sky, casting a warm glow over the breathtaking coastline. A tribute to the awe-inspiring beauty of this natural wonder.",
    averageRating: 5,
    type: "landscape",
    sizes: [
      { dimensions: "55 x 40 cm", price: 370 },
      { dimensions: "70 x 50 cm", price: 480 },
      { dimensions: "85 x 60 cm", price: 590 },
      { dimensions: "100 x 70 cm", price: 700 },
      { dimensions: "120 x 85 cm", price: 810 },
      { dimensions: "140 x 100 cm", price: 920 },
    ],
    reviews: [
      {
        name: "Charlotte W.",
        date: "September 5, 2025",
        rating: 5,
        text: "This piece captures the dramatic beauty of the Cliffs of Dover perfectly. The brushstrokes give it such life!",
      },
      {
        name: "James T.",
        date: "September 7, 2025",
        rating: 5,
        text: "A stunning blend of color and movement. It truly feels like standing on the edge of these magnificent cliffs.",
      },
      {
        name: "Olivia H.",
        date: "September 8, 2025",
        rating: 4,
        text: "A beautiful impressionist take! I wish the sky had a little more contrast, but overall a fantastic painting.",
      },
      {
        name: "Daniel K.",
        date: "September 9, 2025",
        rating: 5,
        text: "Absolutely mesmerizing. The depth and texture make it feel like the waves are moving before my eyes.",
      },
      {
        name: "Sophia L.",
        date: "September 10, 2025",
        rating: 5,
        text: "A perfect balance of detail and impressionist expression. This piece brings so much serenity to my home!",
      },
    ],
  },
  {
    id: uuidv4(),
    title: "Parisian Elegance",
    artist: "Juliette Morel",
    image: "/images/parisian_elegance.webp",
    description:
      "The Eiffel Tower rises gracefully above the Parisian skyline, bathed in soft sunlight. Expressive brushstrokes bring out the intricate latticework, while the dreamy hues of the city below evoke the romance and charm of Paris. A stunning impressionist masterpiece capturing the essence of the City of Light.",
    averageRating: 5,
    type: "landscape",
    sizes: [
      { dimensions: "55 x 40 cm", price: 380 },
      { dimensions: "70 x 50 cm", price: 490 },
      { dimensions: "85 x 60 cm", price: 600 },
      { dimensions: "100 x 70 cm", price: 710 },
      { dimensions: "120 x 85 cm", price: 820 },
      { dimensions: "140 x 100 cm", price: 930 },
    ],
    reviews: [
      {
        name: "Amelie L.",
        date: "September 15, 2025",
        rating: 5,
        text: "Absolutely breathtaking! The colors and movement bring Paris to life in a magical way.",
      },
      {
        name: "Lucas M.",
        date: "September 17, 2025",
        rating: 5,
        text: "The brushstrokes make this painting feel so alive! A must-have for any Paris lover.",
      },
      {
        name: "Emma C.",
        date: "September 18, 2025",
        rating: 4,
        text: "A beautiful piece! I love the detail in the Eiffel Tower, though I wish the foreground had a bit more contrast.",
      },
      {
        name: "Noah R.",
        date: "September 19, 2025",
        rating: 5,
        text: "The way the light plays across the tower is stunning. It brings such elegance to my space!",
      },
      {
        name: "Sophia T.",
        date: "September 20, 2025",
        rating: 5,
        text: "This painting captures everything I love about Paris—romance, beauty, and timeless charm!",
      },
    ],
  },
  {
    id: uuidv4(),
    title: "Eternal Venice",
    artist: "Alessandro Fiorini",
    image: "/images/eternal_venice.webp",
    description:
      "The enchanting canals of Venice come to life in this impressionist masterpiece. Gondolas drift through shimmering waters, reflecting the warm glow of lanterns and historic architecture. Expressive brushstrokes capture the romance and timeless charm of this breathtaking city, evoking a dreamlike atmosphere.",
    averageRating: 5,
    type: "landscape",
    sizes: [
      { dimensions: "55 x 40 cm", price: 390 },
      { dimensions: "70 x 50 cm", price: 500 },
      { dimensions: "85 x 60 cm", price: 610 },
      { dimensions: "100 x 70 cm", price: 720 },
      { dimensions: "120 x 85 cm", price: 830 },
      { dimensions: "140 x 100 cm", price: 940 },
    ],
    reviews: [
      {
        name: "Giulia M.",
        date: "September 25, 2025",
        rating: 5,
        text: "This painting perfectly captures the magic of Venice! The water reflections are absolutely stunning.",
      },
      {
        name: "Leonardo P.",
        date: "September 27, 2025",
        rating: 5,
        text: "I feel like I’m walking along the canals every time I look at this masterpiece. A truly remarkable piece!",
      },
      {
        name: "Clara B.",
        date: "September 28, 2025",
        rating: 4,
        text: "Beautiful work! I love the colors, but I wish there was a bit more contrast in the sky.",
      },
      {
        name: "Marco D.",
        date: "September 29, 2025",
        rating: 5,
        text: "The movement of the water is so well captured—it feels alive! A must-have for lovers of Venice.",
      },
      {
        name: "Sophia L.",
        date: "September 30, 2025",
        rating: 5,
        text: "Absolutely mesmerizing! This painting brings the romance of Venice right into my home.",
      },
    ],
  },
  {
    id: uuidv4(),
    title: "Valley of Light",
    artist: "Matteo Lavigne",
    image: "/images/valley_of_light.webp",
    description:
      "Rolling green hills and distant mountains frame a serene valley, where a river winds gracefully through golden fields. Expressive impressionist brushstrokes capture the warmth of sunlight and the gentle movement of nature, evoking a sense of peace and untouched beauty.",
    averageRating: 5,
    type: "landscape",
    sizes: [
      { dimensions: "55 x 40 cm", price: 380 },
      { dimensions: "70 x 50 cm", price: 490 },
      { dimensions: "85 x 60 cm", price: 600 },
      { dimensions: "100 x 70 cm", price: 710 },
      { dimensions: "120 x 85 cm", price: 820 },
      { dimensions: "140 x 100 cm", price: 930 },
    ],
    reviews: [
      {
        name: "Amelia F.",
        date: "October 5, 2025",
        rating: 5,
        text: "This painting brings such a sense of peace to my home! The brushstrokes make the valley feel so alive.",
      },
      {
        name: "Ethan R.",
        date: "October 7, 2025",
        rating: 5,
        text: "A breathtaking piece! The way the sunlight plays over the hills is stunning.",
      },
      {
        name: "Olivia T.",
        date: "October 8, 2025",
        rating: 4,
        text: "I love the colors, but I wish the river had a bit more detail. Still, an amazing piece!",
      },
      {
        name: "Daniel L.",
        date: "October 9, 2025",
        rating: 5,
        text: "A perfect mix of depth and softness. It truly captures the beauty of untouched nature.",
      },
      {
        name: "Sophia N.",
        date: "October 10, 2025",
        rating: 5,
        text: "This artwork makes me feel like I’m standing in the middle of a sunlit valley. Absolutely stunning!",
      },
    ],
  },
  {
    id: uuidv4(),
    title: "Sacred Heights of Tibet",
    artist: "Tenzing Norbu",
    image: "/images/sacred_heights_of_tibet.webp",
    description:
      "Snow-capped mountains tower over the vast Tibetan valleys, where a winding river reflects the golden hues of the sky. Vibrant monasteries and prayer flags bring a spiritual energy to the landscape, captured through expressive impressionist brushstrokes. A breathtaking tribute to Tibet’s serene and majestic beauty.",
    averageRating: 5,
    type: "landscape",
    sizes: [
      { dimensions: "55 x 40 cm", price: 400 },
      { dimensions: "70 x 50 cm", price: 510 },
      { dimensions: "85 x 60 cm", price: 620 },
      { dimensions: "100 x 70 cm", price: 730 },
      { dimensions: "120 x 85 cm", price: 840 },
      { dimensions: "140 x 100 cm", price: 950 },
    ],
    reviews: [
      {
        name: "Lobsang T.",
        date: "October 15, 2025",
        rating: 5,
        text: "This painting perfectly captures the spirit of Tibet. The mountains feel alive with energy!",
      },
      {
        name: "Emily R.",
        date: "October 17, 2025",
        rating: 5,
        text: "The brushstrokes create such a wonderful sense of movement. It’s a masterpiece!",
      },
      {
        name: "Nathan P.",
        date: "October 18, 2025",
        rating: 4,
        text: "I love the monastery details, but I wish the river was a bit more defined. Still, an incredible work of art.",
      },
      {
        name: "Sophie D.",
        date: "October 19, 2025",
        rating: 5,
        text: "A breathtaking scene! The use of light and shadow makes it feel so peaceful yet powerful.",
      },
      {
        name: "Noah K.",
        date: "October 20, 2025",
        rating: 5,
        text: "This piece transports me to the heart of Tibet. The colors and depth are stunning!",
      },
    ],
  },
  {
    id: uuidv4(),
    title: "Eternal Peaks of the Himalayas",
    artist: "Surya Patel",
    image: "/images/eternal_peaks_of_the_himalayas.webp",
    description:
      "The majestic Himalayas rise into the sky, their snow-capped peaks bathed in golden light. Expressive impressionist brushstrokes bring the movement of clouds and icy slopes to life, evoking a breathtaking sense of tranquility and power. A timeless tribute to one of Earth’s most awe-inspiring landscapes.",
    averageRating: 5,
    type: "square",
    sizes: [
      { dimensions: "40 x 40 cm", price: 410 },
      { dimensions: "50 x 50 cm", price: 520 },
      { dimensions: "60 x 60 cm", price: 630 },
      { dimensions: "70 x 70 cm", price: 740 },
      { dimensions: "85 x 85 cm", price: 850 },
      { dimensions: "100 x 100 cm", price: 960 },
    ],
    reviews: [
      {
        name: "Kiran R.",
        date: "October 25, 2025",
        rating: 5,
        text: "Absolutely breathtaking! The light on the peaks makes them feel alive.",
      },
      {
        name: "Elena M.",
        date: "October 27, 2025",
        rating: 5,
        text: "The depth and brushwork are phenomenal. It feels like I’m staring at the Himalayas from my window!",
      },
      {
        name: "Daniel K.",
        date: "October 28, 2025",
        rating: 4,
        text: "The sky is mesmerizing, but I wish there was a bit more shadow detail on the slopes. Still a masterpiece!",
      },
      {
        name: "Sophia P.",
        date: "October 29, 2025",
        rating: 5,
        text: "The impressionist style makes this landscape feel magical and dreamlike. I love it!",
      },
      {
        name: "Noah T.",
        date: "October 30, 2025",
        rating: 5,
        text: "This painting captures the pure grandeur of the Himalayas. An absolute must-have for mountain lovers.",
      },
    ],
  },
  {
    id: uuidv4(),
    title: "Tranquil Shoreline",
    artist: "Emilia Laurent",
    image: "/images/tranquil_shoreline.webp",
    description:
      "Golden sands stretch along the shoreline as gentle turquoise waves roll onto the beach. Expressive impressionist brushstrokes bring movement to the water and sky, creating a soft, dreamy atmosphere. A peaceful and evocative tribute to the serenity of the sea.",
    averageRating: 5,
    type: "landscape",
    sizes: [
      { dimensions: "55 x 40 cm", price: 380 },
      { dimensions: "70 x 50 cm", price: 490 },
      { dimensions: "85 x 60 cm", price: 600 },
      { dimensions: "100 x 70 cm", price: 710 },
      { dimensions: "120 x 85 cm", price: 820 },
      { dimensions: "140 x 100 cm", price: 930 },
    ],
    reviews: [
      {
        name: "Olivia H.",
        date: "November 5, 2025",
        rating: 5,
        text: "Looking at this painting makes me feel like I’m on a beach getaway. The colors are so soothing!",
      },
      {
        name: "Daniel R.",
        date: "November 7, 2025",
        rating: 5,
        text: "The brushstrokes perfectly capture the movement of the waves. A stunning piece!",
      },
      {
        name: "Sophia L.",
        date: "November 8, 2025",
        rating: 4,
        text: "A beautiful painting! I just wish the sand had a little more texture, but otherwise perfect.",
      },
      {
        name: "Ethan M.",
        date: "November 9, 2025",
        rating: 5,
        text: "I can almost hear the waves crashing. The impressionist style adds such a dreamy feel.",
      },
      {
        name: "Charlotte T.",
        date: "November 10, 2025",
        rating: 5,
        text: "This is exactly what I needed for my beach house. It’s peaceful, bright, and absolutely gorgeous!",
      },
    ],
  },
  {
    id: uuidv4(),
    title: "Tempest in the Sky",
    artist: "Elias Varnen",
    image: "/images/tempest_in_the_sky.webp",
    description:
      "Dark storm clouds swirl in a dramatic dance of blues and grays, illuminated by brilliant flashes of lightning. Expressive impressionist brushstrokes bring the movement of the storm to life, blending power and beauty in a breathtaking composition. A stunning portrayal of nature’s raw energy.",
    averageRating: 5,
    type: "landscape",
    sizes: [
      { dimensions: "55 x 40 cm", price: 390 },
      { dimensions: "70 x 50 cm", price: 500 },
      { dimensions: "85 x 60 cm", price: 610 },
      { dimensions: "100 x 70 cm", price: 720 },
      { dimensions: "120 x 85 cm", price: 830 },
      { dimensions: "140 x 100 cm", price: 940 },
    ],
    reviews: [
      {
        name: "Alexander M.",
        date: "November 15, 2025",
        rating: 5,
        text: "The energy in this painting is incredible! It really captures the power of a storm.",
      },
      {
        name: "Sophia W.",
        date: "November 17, 2025",
        rating: 5,
        text: "The lightning and movement of the clouds are mesmerizing. Such a dramatic and stunning piece!",
      },
      {
        name: "Ethan K.",
        date: "November 18, 2025",
        rating: 4,
        text: "A breathtaking composition. I only wish the contrast in the clouds was a little stronger.",
      },
      {
        name: "Liam T.",
        date: "November 19, 2025",
        rating: 5,
        text: "This artwork makes me feel like I’m standing right under the storm. It’s so vivid and intense!",
      },
      {
        name: "Charlotte P.",
        date: "November 20, 2025",
        rating: 5,
        text: "Absolutely electrifying! This is the perfect statement piece for my living room.",
      },
    ],
  },
];

// Add new fields afterwards to the data
const updatedArtworks = artworks.map((artwork) => ({
  ...artwork,
  width:
    artwork.type === "landscape"
      ? 1792
      : artwork.type === "portrait"
      ? 1024
      : 1024,
  height:
    artwork.type === "landscape"
      ? 1024
      : artwork.type === "portrait"
      ? 1792
      : 1024,
  averageRating: artwork.reviews.length
    ? artwork.reviews.reduce((acc, review) => acc + review.rating, 0) /
      artwork.reviews.length
    : 0,
}));

export default updatedArtworks;
