const artworks = [
  {
    id: "c3d5718f-155f-4ad1-a970-e6383db94b18",
    title: "A Vision in Color",
    artist: "Liora Senn",
    image: {
      type: "portrait",
      width: 1024,
      height: 1792,
      uri: "/images/a_vision_in_color.webp",
    },
    description:
      "Bold brushstrokes and rich hues of purple, blue, and red bring this abstract masterpiece to life. A striking blend of movement and emotion, this piece captures energy and depth in every layer.",
    averageRating: 4.5,
    type: "portrait",
    sizes: [
      { width: 40, height: 55, price: 350 },
      { width: 50, height: 70, price: 450 },
      { width: 60, height: 85, price: 550 },
      { width: 70, height: 100, price: 650 },
      { width: 85, height: 120, price: 750 },
      { width: 100, height: 140, price: 850 },
    ],
    reviews: [
      {
        name: "Sarah M.",
        date: "2025-01-09T22:00:00.000Z",
        rating: 5,
        text: "Absolutely stunning! The colors are vibrant, and the details are even more breathtaking in person.",
      },
      {
        name: "John D.",
        date: "2025-02-04T22:00:00.000Z",
        rating: 4,
        text: "Beautiful artwork, but the frame was slightly scratched upon arrival. Still a great piece!",
      },
    ],
  },
  {
    id: "845727d8-99c9-4035-99f9-76348903dd77",
    title: "The Spirit of Freedom",
    artist: "Elias Varnen",
    image: {
      type: "landscape",
      width: 1792,
      height: 1024,
      uri: "/images/the_spirit_of_freedom.webp",
    },
    description:
      "Vivid colors and flowing forms embody the untamed essence of movement. This artwork captures the raw energy and boundless freedom of a soul unrestrained.",
    averageRating: 5,
    type: "landscape",
    sizes: [
      { width: 55, height: 40, price: 300 },
      { width: 70, height: 50, price: 400 },
      { width: 85, height: 60, price: 500 },
      { width: 100, height: 70, price: 600 },
      { width: 120, height: 85, price: 700 },
      { width: 140, height: 100, price: 800 },
    ],
    reviews: [
      {
        name: "Emily R.",
        date: "2025-03-07T22:00:00.000Z",
        rating: 5,
        text: "This piece brought so much life into my living room. Highly recommended!",
      },
      {
        name: "Liam K.",
        date: "2025-03-31T21:00:00.000Z",
        rating: 5,
        text: "Even more beautiful in person than online. Great quality!",
      },
    ],
  },
  {
    id: "24771cf6-9196-444f-a5d2-3fa0e75e87bf",
    title: "Whispers of the Bloom",
    artist: "Camille Verdain",
    image: {
      type: "landscape",
      width: 1792,
      height: 1024,
      uri: "/images/whispers_of_the_bloom.webp",
    },
    description:
      "An impressionist vision of a sunlit poppy field, where vivid colors and dynamic brushstrokes capture the beauty of nature in motion.",
    averageRating: 5,
    type: "landscape",
    sizes: [
      { width: 60, height: 45, price: 250 },
      { width: 75, height: 55, price: 350 },
      { width: 90, height: 65, price: 450 },
      { width: 110, height: 80, price: 550 },
      { width: 130, height: 95, price: 650 },
      { width: 150, height: 110, price: 750 },
    ],
    reviews: [
      {
        name: "Olivia P.",
        date: "2025-06-21T21:00:00.000Z",
        rating: 5,
        text: "Absolutely love this piece! It fits perfectly in my dining room.",
      },
    ],
  },
  {
    id: "8b68fe4a-338d-4687-88e2-c7a354fa764a",
    title: "Guardian of Healing",
    artist: "Lucien Moreau",
    image: {
      type: "square",
      width: 1024,
      height: 1024,
      uri: "/images/guardian_of_healing.webp",
    },
    description:
      "A quiet devotion unfolds in flowing color, where light and movement intertwine with the weight of knowledge and the urgency of compassion. Each brushstroke lingers, a testament to hands that heal and time that passes.",
    averageRating: 4,
    type: "square",
    sizes: [
      { width: 55, height: 40, price: 300 },
      { width: 70, height: 50, price: 400 },
      { width: 85, height: 60, price: 500 },
      { width: 100, height: 70, price: 600 },
      { width: 120, height: 85, price: 700 },
      { width: 140, height: 100, price: 800 },
    ],
    reviews: [
      {
        name: "Noah W.",
        date: "2025-05-14T21:00:00.000Z",
        rating: 4,
        text: "A great addition to my office, but shipping took longer than expected.",
      },
    ],
  },
  {
    id: "cd609608-7554-436e-8aa2-2e0cebffe7d2",
    title: "Sunflowers at Dusk",
    artist: "Elias Varnen",
    image: {
      type: "landscape",
      width: 1792,
      height: 1024,
      uri: "/images/sunflowers_at_dusk.webp",
    },
    description:
      "An impressionist vision of a sunflower field at dusk, where vibrant yellows and warm golden hues dance across the canvas, brought to life by dynamic brushstrokes that capture the fleeting beauty of twilight.",
    averageRating: 5,
    type: "landscape",
    sizes: [
      { width: 58, height: 42, price: 200 },
      { width: 72, height: 52, price: 300 },
      { width: 88, height: 65, price: 400 },
      { width: 105, height: 75, price: 500 },
      { width: 125, height: 90, price: 600 },
      { width: 145, height: 105, price: 700 },
    ],
    reviews: [
      {
        name: "James C.",
        date: "2025-07-29T21:00:00.000Z",
        rating: 5,
        text: "The details in this painting are incredible. Looks even better in natural light!",
      },
      {
        name: "Sophia L.",
        date: "2025-08-11T21:00:00.000Z",
        rating: 5,
        text: "The colors are so rich and deep. Perfect for my bedroom!",
      },
    ],
  },
  {
    id: "d092bef3-665d-489a-b7f6-e6bb7bdaad8c",
    title: "Whispering Canopy",
    artist: "Marc Monnet",
    image: {
      type: "square",
      width: 1024,
      height: 1024,
      uri: "/images/whispering_canopy.webp",
    },
    description:
      "A mesmerizing woodland scene where sunlight filters through dense foliage, casting an ethereal glow on the forest path. Rich in greens and deep blues, this painting evokes serenity and mystery, drawing viewers into nature’s embrace.",
    averageRating: 0,
    type: "square",
    sizes: [
      { width: 40, height: 55, price: 375 },
      { width: 50, height: 70, price: 475 },
      { width: 60, height: 85, price: 575 },
      { width: 70, height: 100, price: 675 },
      { width: 85, height: 120, price: 775 },
      { width: 100, height: 140, price: 875 },
    ],
    reviews: [],
  },
  {
    id: "d9e89855-4ee1-4e93-9e06-23d716f70df2",
    title: "Golden Metropolis",
    artist: "Elijah Carter",
    image: {
      type: "portrait",
      width: 1024,
      height: 1792,
      uri: "/images/golden_metropolis.webp",
    },
    description:
      "A breathtaking cityscape bathed in golden hues as the sunlight reflects off towering skyscrapers. Thick, textured brushstrokes create a dynamic sense of movement in this bustling urban scene, capturing the energy and vibrancy of city life.",
    averageRating: 0,
    type: "portrait",
    sizes: [
      { width: 40, height: 55, price: 400 },
      { width: 50, height: 70, price: 500 },
      { width: 60, height: 85, price: 600 },
      { width: 70, height: 100, price: 700 },
      { width: 85, height: 120, price: 800 },
      { width: 100, height: 140, price: 900 },
    ],
    reviews: [],
  },
  {
    id: "aec7e977-6e59-410a-a58d-f4efe4327305",
    title: "Twilight Reflections",
    artist: "Nathaniel Harper",
    image: {
      type: "square",
      width: 1024,
      height: 1024,
      uri: "/images/twilight_reflections.webp",
    },
    description:
      "An enchanting city skyline illuminated by the warm glow of twilight. The vibrant mix of purples, oranges, and blues brings depth and emotion to this mesmerizing urban scene, where reflections dance on the shimmering water below.",
    averageRating: 0,
    type: "square",
    sizes: [
      { width: 40, height: 55, price: 420 },
      { width: 50, height: 70, price: 520 },
      { width: 60, height: 85, price: 620 },
      { width: 70, height: 100, price: 720 },
      { width: 85, height: 120, price: 820 },
      { width: 100, height: 140, price: 920 },
    ],
    reviews: [],
  },
  {
    id: "c96bac5d-3d95-438f-8194-7616d0933efc",
    title: "Tempest’s Dance",
    artist: "Isla Davenport",
    image: {
      type: "landscape",
      width: 1792,
      height: 1024,
      uri: "/images/tempest_dance.webp",
    },
    description:
      "Powerful waves crash and swirl in this mesmerizing seascape, capturing the raw energy and movement of the ocean. The rich blues, greens, and whites blend seamlessly, creating a sense of both chaos and harmony in this breathtaking painting.",
    averageRating: 0,
    type: "landscape",
    sizes: [
      { width: 40, height: 55, price: 430 },
      { width: 50, height: 70, price: 530 },
      { width: 60, height: 85, price: 630 },
      { width: 70, height: 100, price: 730 },
      { width: 85, height: 120, price: 830 },
      { width: 100, height: 140, price: 930 },
    ],
    reviews: [],
  },
  {
    id: "ea7782cf-e921-42b5-a82c-a945145a98ad",
    title: "Meadow Serenity",
    artist: "Eleanor Marchand",
    image: {
      type: "landscape",
      width: 1792,
      height: 1024,
      uri: "/images/meadow_serenity.webp",
    },
    description:
      "A tranquil river winds through a lush, colorful meadow, bathed in the golden glow of a serene afternoon. Soft brushstrokes and a rich palette of greens, yellows, and wildflower hues bring this peaceful landscape to life, evoking a sense of harmony and calm.",
    averageRating: 0,
    type: "landscape",
    sizes: [
      { width: 40, height: 55, price: 410 },
      { width: 50, height: 70, price: 510 },
      { width: 60, height: 85, price: 610 },
      { width: 70, height: 100, price: 710 },
      { width: 85, height: 120, price: 810 },
      { width: 100, height: 140, price: 910 },
    ],
    reviews: [],
  },
  {
    id: "65724846-a5c0-42de-85ec-f09aacb1add8",
    title: "Majestic Peaks",
    artist: "Julian Ashford",
    image: {
      type: "square",
      width: 1024,
      height: 1024,
      uri: "/images/majestic_peaks.webp",
    },
    description:
      "A breathtaking mountain range bathed in the golden hues of dawn. Snow-capped peaks rise dramatically above a tranquil lake, as mist gently rolls over the valleys. This stunning landscape captures the grandeur and serenity of nature at its finest.",
    averageRating: 0,
    type: "square",
    sizes: [
      { width: 40, height: 55, price: 450 },
      { width: 50, height: 70, price: 550 },
      { width: 60, height: 85, price: 650 },
      { width: 70, height: 100, price: 750 },
      { width: 85, height: 120, price: 850 },
      { width: 100, height: 140, price: 950 },
    ],
    reviews: [],
  },
  {
    id: "3d3c3c7e-eb45-4eb7-803d-4fb54f36caa7",
    title: "Whispering Falls",
    artist: "Elias Varnen",
    image: {
      type: "landscape",
      width: 1792,
      height: 1024,
      uri: "/images/whispering_falls.webp",
    },
    description:
      "An impressionist masterpiece capturing the ethereal beauty of a cascading waterfall surrounded by lush greenery. The vibrant brushstrokes and dreamy colors bring the scene to life, evoking a sense of movement and tranquility.",
    averageRating: 4.5,
    type: "landscape",
    sizes: [
      { width: 55, height: 40, price: 320 },
      { width: 70, height: 50, price: 430 },
      { width: 85, height: 60, price: 540 },
      { width: 100, height: 70, price: 650 },
      { width: 120, height: 85, price: 760 },
      { width: 140, height: 100, price: 870 },
    ],
    reviews: [
      {
        name: "Olivia S.",
        date: "2025-05-01T21:00:00.000Z",
        rating: 5,
        text: "The brushstrokes and colors give this piece so much life. It feels like standing in front of a real waterfall!",
      },
      {
        name: "James L.",
        date: "2025-05-04T21:00:00.000Z",
        rating: 4,
        text: "Absolutely stunning work. The impressionist style makes it feel timeless and full of energy!",
      },
    ],
  },
  {
    id: "287efb19-e9e1-4ae9-9042-0375b3f9922f",
    title: "Golden Horizon",
    artist: "Elias Varnen",
    image: {
      type: "landscape",
      width: 1792,
      height: 1024,
      uri: "/images/golden_horizon.webp",
    },
    description:
      "Rolling green hills bathed in golden sunlight stretch into the horizon. The textured brushstrokes capture the wind dancing through the grass, while the soft pastel sky adds depth and warmth. A truly serene and timeless landscape.",
    averageRating: 4.5,
    type: "landscape",
    sizes: [
      { width: 55, height: 40, price: 320 },
      { width: 70, height: 50, price: 430 },
      { width: 85, height: 60, price: 540 },
      { width: 100, height: 70, price: 650 },
      { width: 120, height: 85, price: 760 },
      { width: 140, height: 100, price: 870 },
    ],
    reviews: [
      {
        name: "Isabella T.",
        date: "2025-05-09T21:00:00.000Z",
        rating: 5,
        text: "This artwork fills my space with warmth and tranquility. The rolling hills feel alive!",
      },
      {
        name: "Ethan W.",
        date: "2025-05-11T21:00:00.000Z",
        rating: 4,
        text: "The texture and colors are absolutely mesmerizing. Perfect for a nature lover!",
      },
    ],
  },
  {
    id: "b7db6f54-c9fa-4541-bf9a-aae5533b7312",
    title: "The Cozy Haven",
    artist: "Livia Marceau",
    image: {
      type: "landscape",
      width: 1792,
      height: 1024,
      uri: "/images/the_cozy_haven.webp",
    },
    description:
      "Nestled among vibrant wildflowers, this picturesque countryside cottage exudes warmth and tranquility. Golden sunlight bathes the stone walls, while a winding path leads to the inviting front door. The impressionist brushstrokes bring life to the trees and sky, making this an enchanting escape into nature.",
    averageRating: 4.666666666666667,
    type: "landscape",
    sizes: [
      { width: 55, height: 40, price: 330 },
      { width: 70, height: 50, price: 440 },
      { width: 85, height: 60, price: 550 },
      { width: 100, height: 70, price: 660 },
      { width: 120, height: 85, price: 770 },
      { width: 140, height: 100, price: 880 },
    ],
    reviews: [
      {
        name: "Amelia V.",
        date: "2025-05-17T21:00:00.000Z",
        rating: 5,
        text: "I feel like I could step into this painting and be transported to a peaceful countryside retreat. Absolutely stunning!",
      },
      {
        name: "Benjamin S.",
        date: "2025-05-19T21:00:00.000Z",
        rating: 4,
        text: "The colors and light in this piece are magical. It brings so much warmth to my home.",
      },
      {
        name: "Charlotte L.",
        date: "2025-05-20T21:00:00.000Z",
        rating: 5,
        text: "This artwork captures everything I love about the countryside—charm, peace, and natural beauty.",
      },
    ],
  },
  {
    id: "562881bc-cc9f-4024-b21e-97ce84b249d5",
    title: "Tempest Unleashed",
    artist: "Victor Ardent",
    image: {
      type: "landscape",
      width: 1792,
      height: 1024,
      uri: "/images/tempest_unleashed.webp",
    },
    description:
      "Towering waves crash against jagged cliffs as storm clouds swirl overhead. A haunting glow filters through the darkness, illuminating the chaotic sea in this breathtaking impressionist masterpiece. The powerful brushstrokes and deep contrasts capture the raw energy and beauty of nature’s untamed force.",
    averageRating: 4.75,
    type: "landscape",
    sizes: [
      { width: 55, height: 40, price: 340 },
      { width: 70, height: 50, price: 450 },
      { width: 85, height: 60, price: 560 },
      { width: 100, height: 70, price: 670 },
      { width: 120, height: 85, price: 780 },
      { width: 140, height: 100, price: 890 },
    ],
    reviews: [
      {
        name: "Nathan R.",
        date: "2025-05-24T21:00:00.000Z",
        rating: 5,
        text: "The movement in this piece is incredible. It feels like the waves could crash right out of the painting!",
      },
      {
        name: "Isla P.",
        date: "2025-05-26T21:00:00.000Z",
        rating: 5,
        text: "The stormy atmosphere gives it such an intense presence. A stunning addition to my collection!",
      },
      {
        name: "Oliver H.",
        date: "2025-05-27T21:00:00.000Z",
        rating: 5,
        text: "The energy in this artwork is captivating. Every time I look at it, I notice new details.",
      },
      {
        name: "Sophia T.",
        date: "2025-05-28T21:00:00.000Z",
        rating: 4,
        text: "The mix of dark tones with the golden light is so striking. Truly a masterpiece!",
      },
    ],
  },
  {
    id: "8cf3f676-16ad-4ac3-b1a6-b5a2f7a3e183",
    title: "City Lights",
    artist: "Marcello Fontaine",
    image: {
      type: "landscape",
      width: 1792,
      height: 1024,
      uri: "/images/city_lights.webp",
    },
    description:
      "A bustling city street at dusk comes alive with shimmering reflections of neon lights on the wet pavement. Silhouetted figures move through the glow of streetlamps, their forms captured in expressive, impressionist brushstrokes. The atmosphere is rich with movement, color, and the timeless beauty of urban life.",
    averageRating: 4.5,
    type: "landscape",
    sizes: [
      { width: 55, height: 40, price: 350 },
      { width: 70, height: 50, price: 460 },
      { width: 85, height: 60, price: 570 },
      { width: 100, height: 70, price: 680 },
      { width: 120, height: 85, price: 790 },
      { width: 140, height: 100, price: 900 },
    ],
    reviews: [
      {
        name: "Daniel J.",
        date: "2025-06-04T21:00:00.000Z",
        rating: 5,
        text: "This piece captures the magic of the city at night so beautifully. The reflections and colors are mesmerizing!",
      },
      {
        name: "Emma K.",
        date: "2025-06-06T21:00:00.000Z",
        rating: 4,
        text: "I love how the movement of people and lights feels so dynamic. A wonderful piece for any urban art lover!",
      },
      {
        name: "Lucas P.",
        date: "2025-06-08T21:00:00.000Z",
        rating: 5,
        text: "This painting brings a lively energy to my living space. It feels like stepping into a city full of life and stories.",
      },
      {
        name: "Sophia W.",
        date: "2025-06-09T21:00:00.000Z",
        rating: 4,
        text: "The atmosphere in this artwork is incredible! The way the lights reflect off the wet pavement is stunning.",
      },
    ],
  },
  {
    id: "de38e55a-f587-4104-94b1-648dd1740570",
    title: "Autumn Serenity",
    artist: "Elara Duvall",
    image: {
      type: "landscape",
      width: 1792,
      height: 1024,
      uri: "/images/autumn_serenity.webp",
    },
    description:
      "Golden leaves blanket the ground as a soft autumn breeze rustles through the trees. A winding path leads through the peaceful park, where warm lamplights glow softly near a reflective pond. Expressive brushstrokes bring a dreamy, nostalgic atmosphere to this stunning impressionist scene.",
    averageRating: 4.8,
    type: "landscape",
    sizes: [
      { width: 55, height: 40, price: 340 },
      { width: 70, height: 50, price: 450 },
      { width: 85, height: 60, price: 560 },
      { width: 100, height: 70, price: 670 },
      { width: 120, height: 85, price: 780 },
      { width: 140, height: 100, price: 890 },
    ],
    reviews: [
      {
        name: "Henry B.",
        date: "2025-06-14T21:00:00.000Z",
        rating: 5,
        text: "This painting reminds me of peaceful autumn walks. The colors are so rich and warm!",
      },
      {
        name: "Olivia M.",
        date: "2025-06-16T21:00:00.000Z",
        rating: 5,
        text: "Absolutely stunning! The reflections and textures make this piece feel so alive.",
      },
      {
        name: "Ethan L.",
        date: "2025-06-17T21:00:00.000Z",
        rating: 5,
        text: "I can almost feel the crisp autumn air. The details in this painting are breathtaking.",
      },
      {
        name: "Sophia C.",
        date: "2025-06-18T21:00:00.000Z",
        rating: 4,
        text: "A wonderful addition to my collection. It brings such a calming presence to my home.",
      },
      {
        name: "Noah W.",
        date: "2025-06-19T21:00:00.000Z",
        rating: 5,
        text: "The glow of the lamplights and the golden leaves create such a cozy feeling. I love it!",
      },
    ],
  },
  {
    id: "47722883-1655-479c-b5b8-9441fccb168f",
    title: "Urban Heights",
    artist: "Sebastian Moreau",
    image: {
      type: "portrait",
      width: 1024,
      height: 1792,
      uri: "/images/urban_heights.webp",
    },
    description:
      "Towering skyscrapers rise into the evening sky, their glass facades glowing with the warm hues of the setting sun. Expressive brushstrokes capture the shimmering reflections and the energy of the bustling city below. A breathtaking vertical composition that evokes the grandeur of modern architecture.",
    averageRating: 4.8,
    type: "portrait",
    sizes: [
      { width: 40, height: 55, price: 360 },
      { width: 50, height: 70, price: 470 },
      { width: 60, height: 85, price: 580 },
      { width: 70, height: 100, price: 690 },
      { width: 85, height: 120, price: 800 },
      { width: 100, height: 140, price: 910 },
    ],
    reviews: [
      {
        name: "Michael D.",
        date: "2025-06-24T21:00:00.000Z",
        rating: 5,
        text: "This piece captures the beauty and energy of the city skyline perfectly! The colors are stunning.",
      },
      {
        name: "Emily R.",
        date: "2025-06-26T21:00:00.000Z",
        rating: 5,
        text: "Absolutely mesmerizing. The sense of height and movement in this painting is incredible.",
      },
      {
        name: "Jacob H.",
        date: "2025-06-27T21:00:00.000Z",
        rating: 5,
        text: "A masterpiece! It brings such a modern and elegant feel to my office.",
      },
      {
        name: "Sophia W.",
        date: "2025-06-28T21:00:00.000Z",
        rating: 4,
        text: "Love the reflections on the buildings. I wish the sky had a bit more contrast, but still an amazing piece!",
      },
      {
        name: "Olivia T.",
        date: "2025-06-29T21:00:00.000Z",
        rating: 5,
        text: "The way the city lights interact with the sunset is just breathtaking. It’s my favorite art piece now!",
      },
    ],
  },
  {
    id: "f28b2d8c-a0be-4b42-b07f-2fc48be0d8ef",
    title: "Reflections of Stillness",
    artist: "Isabelle Laurent",
    image: {
      type: "landscape",
      width: 1792,
      height: 1024,
      uri: "/images/reflections_of_stillness.webp",
    },
    description:
      "A tranquil lake mirrors the soft hues of the sky as golden sunlight filters through the trees. Gentle ripples dance across the water, adding depth and movement to this serene scene. Expressive brushstrokes bring warmth and harmony, making this impressionist masterpiece a window into nature’s peaceful embrace.",
    averageRating: 4.8,
    type: "landscape",
    sizes: [
      { width: 55, height: 40, price: 350 },
      { width: 70, height: 50, price: 460 },
      { width: 85, height: 60, price: 570 },
      { width: 100, height: 70, price: 680 },
      { width: 120, height: 85, price: 790 },
      { width: 140, height: 100, price: 900 },
    ],
    reviews: [
      {
        name: "Charlotte M.",
        date: "2025-07-04T21:00:00.000Z",
        rating: 5,
        text: "The reflections on the lake are mesmerizing. It brings such a calming presence to my space!",
      },
      {
        name: "Daniel S.",
        date: "2025-07-06T21:00:00.000Z",
        rating: 5,
        text: "This painting makes me feel like I’m standing by the water at sunset. Absolutely stunning.",
      },
      {
        name: "Emma R.",
        date: "2025-07-07T21:00:00.000Z",
        rating: 4,
        text: "A beautiful piece! I wish there was a little more contrast in the sky, but the colors are lovely.",
      },
      {
        name: "Lucas B.",
        date: "2025-07-08T21:00:00.000Z",
        rating: 5,
        text: "This painting captures the essence of serenity. The brushstrokes add such a dreamy touch!",
      },
      {
        name: "Sophia L.",
        date: "2025-07-09T21:00:00.000Z",
        rating: 5,
        text: "A true masterpiece! The play of light on the water is so enchanting.",
      },
    ],
  },
  {
    id: "9f2c0d7f-522f-4551-aabf-0227c34a7aeb",
    title: "Emerald Wilderness",
    artist: "Lucien Navarro",
    image: {
      type: "square",
      width: 1024,
      height: 1024,
      uri: "/images/emerald_wilderness.webp",
    },
    description:
      "Dense and untamed, this vibrant jungle scene captures the raw beauty of nature. Sunlight pierces through the canopy, illuminating the rich greenery and bursts of exotic flowers. Expressive impressionist brushstrokes bring movement to the foliage, creating an immersive escape into the heart of the wild.",
    averageRating: 4.8,
    type: "square",
    sizes: [
      { width: 40, height: 40, price: 340 },
      { width: 50, height: 50, price: 450 },
      { width: 60, height: 60, price: 560 },
      { width: 70, height: 70, price: 670 },
      { width: 85, height: 85, price: 780 },
      { width: 100, height: 100, price: 890 },
    ],
    reviews: [
      {
        name: "Ethan R.",
        date: "2025-07-14T21:00:00.000Z",
        rating: 5,
        text: "The lush greenery feels so alive! This painting adds such a refreshing vibe to my home.",
      },
      {
        name: "Amelia T.",
        date: "2025-07-16T21:00:00.000Z",
        rating: 5,
        text: "Absolutely stunning. The light filtering through the trees is captured beautifully.",
      },
      {
        name: "James L.",
        date: "2025-07-17T21:00:00.000Z",
        rating: 4,
        text: "Love the wild feel of this piece. I wish there were even more vibrant flowers for contrast.",
      },
      {
        name: "Sophia N.",
        date: "2025-07-18T21:00:00.000Z",
        rating: 5,
        text: "A gorgeous representation of nature’s untouched beauty. The brushstrokes are mesmerizing!",
      },
      {
        name: "Noah P.",
        date: "2025-07-19T21:00:00.000Z",
        rating: 5,
        text: "It feels like stepping into a jungle. The textures and colors are just perfect.",
      },
    ],
  },
  {
    id: "51770d98-2eed-4bb5-a03f-3db6c1665b49",
    title: "Fragmented Identity",
    artist: "Nico Vargas",
    image: {
      type: "portrait",
      width: 1024,
      height: 1792,
      uri: "/images/fragmented_identity.webp",
    },
    description:
      "A bold and expressive cubist portrait, deconstructing the human form into dynamic geometric shapes and overlapping perspectives. Vivid contrasts of color and fragmented planes create a striking sense of depth and emotion, inviting the viewer to interpret multiple facets of identity.",
    averageRating: 4.8,
    type: "portrait",
    sizes: [
      { width: 40, height: 55, price: 370 },
      { width: 50, height: 70, price: 480 },
      { width: 60, height: 85, price: 590 },
      { width: 70, height: 100, price: 700 },
      { width: 85, height: 120, price: 810 },
      { width: 100, height: 140, price: 920 },
    ],
    reviews: [
      {
        name: "Liam D.",
        date: "2025-07-24T21:00:00.000Z",
        rating: 5,
        text: "The cubist style is mesmerizing! The fragmented shapes give such a unique personality to this piece.",
      },
      {
        name: "Sophia M.",
        date: "2025-07-26T21:00:00.000Z",
        rating: 5,
        text: "A striking and thought-provoking portrait. The bold colors and angles make it feel alive!",
      },
      {
        name: "Ethan K.",
        date: "2025-07-27T21:00:00.000Z",
        rating: 4,
        text: "I love the abstraction, though I wish the colors were slightly softer. Still a fantastic piece!",
      },
      {
        name: "Olivia P.",
        date: "2025-07-28T21:00:00.000Z",
        rating: 5,
        text: "Absolutely stunning! The depth and complexity of the portrait keep me coming back to see more details.",
      },
      {
        name: "Noah J.",
        date: "2025-07-29T21:00:00.000Z",
        rating: 5,
        text: "This is a conversation starter for sure! A masterpiece of modern cubism.",
      },
    ],
  },
  {
    id: "951b867b-fc6e-4453-92df-54a244180696",
    title: "Defender of the Nation",
    artist: "Viktor Sokolov",
    image: {
      type: "portrait",
      width: 1024,
      height: 1792,
      uri: "/images/defender_of_the_nation.webp",
    },
    description:
      "A striking impressionist-style propaganda poster featuring a heroic soldier standing with unwavering resolve. Expressive brushstrokes bring life to the determined gaze and strong posture, while the patriotic background evokes unity and strength. A bold and inspiring piece that merges history with artistic expression.",
    averageRating: 4.8,
    type: "portrait",
    sizes: [
      { width: 40, height: 55, price: 380 },
      { width: 50, height: 70, price: 490 },
      { width: 60, height: 85, price: 600 },
      { width: 70, height: 100, price: 710 },
      { width: 85, height: 120, price: 820 },
      { width: 100, height: 140, price: 930 },
    ],
    reviews: [
      {
        name: "Alexei M.",
        date: "2025-08-04T21:00:00.000Z",
        rating: 5,
        text: "This piece captures the strength and determination of a true defender. The brushwork adds so much depth!",
      },
      {
        name: "Elena V.",
        date: "2025-08-06T21:00:00.000Z",
        rating: 5,
        text: "A powerful and emotional artwork. The colors and expression make it a true masterpiece!",
      },
      {
        name: "Mark T.",
        date: "2025-08-07T21:00:00.000Z",
        rating: 4,
        text: "I love the impressionist take on a propaganda poster. The textures are fantastic!",
      },
      {
        name: "Sophie R.",
        date: "2025-08-08T21:00:00.000Z",
        rating: 5,
        text: "This artwork feels historic and modern at the same time. The energy is amazing!",
      },
      {
        name: "Nikolai P.",
        date: "2025-08-09T21:00:00.000Z",
        rating: 5,
        text: "A bold and inspiring piece. It would make a great centerpiece in any collection!",
      },
    ],
  },
  {
    id: "8ee55375-0604-4928-81c8-6666e21299c9",
    title: "Monolithic Silence",
    artist: "Adrian Kovacs",
    image: {
      type: "landscape",
      width: 1792,
      height: 1024,
      uri: "/images/monolithic_silence.webp",
    },
    description:
      "Towering brutalist structures rise against a moody sky, their geometric forms casting deep shadows over the raw concrete landscape. Expressive brushstrokes soften the rigid geometry, blending light and shadow to create an atmospheric dreamlike effect. A powerful tribute to the beauty of brutalism through impressionist abstraction.",
    averageRating: 4.8,
    type: "landscape",
    sizes: [
      { width: 55, height: 40, price: 360 },
      { width: 70, height: 50, price: 470 },
      { width: 85, height: 60, price: 580 },
      { width: 100, height: 70, price: 690 },
      { width: 120, height: 85, price: 800 },
      { width: 140, height: 100, price: 910 },
    ],
    reviews: [
      {
        name: "Liam H.",
        date: "2025-08-24T21:00:00.000Z",
        rating: 5,
        text: "The depth and weight of this piece are incredible. It captures the essence of brutalism perfectly!",
      },
      {
        name: "Isabelle F.",
        date: "2025-08-26T21:00:00.000Z",
        rating: 5,
        text: "A hauntingly beautiful depiction of brutalist architecture. The interplay of light and shadow is mesmerizing.",
      },
      {
        name: "Nathan R.",
        date: "2025-08-27T21:00:00.000Z",
        rating: 4,
        text: "I love the composition, but I wish there were a bit more contrast in the concrete textures.",
      },
      {
        name: "Sophia W.",
        date: "2025-08-28T21:00:00.000Z",
        rating: 5,
        text: "The atmosphere in this painting is intense and thought-provoking. A must-have for modern architecture lovers!",
      },
      {
        name: "Oliver T.",
        date: "2025-08-29T21:00:00.000Z",
        rating: 5,
        text: "It feels like stepping into a dystopian yet fascinating world. The brushstrokes add so much personality to the concrete.",
      },
    ],
  },
  {
    id: "3144b7d5-f99b-4511-b9de-60053b58bb30",
    title: "Majestic Cliffs",
    artist: "William Ashford",
    image: {
      type: "landscape",
      width: 1792,
      height: 1024,
      uri: "/images/majestic_cliffs.webp",
    },
    description:
      "The towering white chalk cliffs of Dover stand proudly against the deep blue sea, their rugged textures brought to life with expressive impressionist brushstrokes. Sunlight filters through a soft, cloudy sky, casting a warm glow over the breathtaking coastline. A tribute to the awe-inspiring beauty of this natural wonder.",
    averageRating: 4.8,
    type: "landscape",
    sizes: [
      { width: 55, height: 40, price: 370 },
      { width: 70, height: 50, price: 480 },
      { width: 85, height: 60, price: 590 },
      { width: 100, height: 70, price: 700 },
      { width: 120, height: 85, price: 810 },
      { width: 140, height: 100, price: 920 },
    ],
    reviews: [
      {
        name: "Charlotte W.",
        date: "2025-09-04T21:00:00.000Z",
        rating: 5,
        text: "This piece captures the dramatic beauty of the Cliffs of Dover perfectly. The brushstrokes give it such life!",
      },
      {
        name: "James T.",
        date: "2025-09-06T21:00:00.000Z",
        rating: 5,
        text: "A stunning blend of color and movement. It truly feels like standing on the edge of these magnificent cliffs.",
      },
      {
        name: "Olivia H.",
        date: "2025-09-07T21:00:00.000Z",
        rating: 4,
        text: "A beautiful impressionist take! I wish the sky had a little more contrast, but overall a fantastic painting.",
      },
      {
        name: "Daniel K.",
        date: "2025-09-08T21:00:00.000Z",
        rating: 5,
        text: "Absolutely mesmerizing. The depth and texture make it feel like the waves are moving before my eyes.",
      },
      {
        name: "Sophia L.",
        date: "2025-09-09T21:00:00.000Z",
        rating: 5,
        text: "A perfect balance of detail and impressionist expression. This piece brings so much serenity to my home!",
      },
    ],
  },
  {
    id: "ae278187-3bdc-405c-a2df-3c1a8ef12b12",
    title: "Parisian Elegance",
    artist: "Juliette Morel",
    image: {
      type: "landscape",
      width: 1792,
      height: 1024,
      uri: "/images/parisian_elegance.webp",
    },
    description:
      "The Eiffel Tower rises gracefully above the Parisian skyline, bathed in soft sunlight. Expressive brushstrokes bring out the intricate latticework, while the dreamy hues of the city below evoke the romance and charm of Paris. A stunning impressionist masterpiece capturing the essence of the City of Light.",
    averageRating: 4.8,
    type: "landscape",
    sizes: [
      { width: 55, height: 40, price: 380 },
      { width: 70, height: 50, price: 490 },
      { width: 85, height: 60, price: 600 },
      { width: 100, height: 70, price: 710 },
      { width: 120, height: 85, price: 820 },
      { width: 140, height: 100, price: 930 },
    ],
    reviews: [
      {
        name: "Amelie L.",
        date: "2025-09-14T21:00:00.000Z",
        rating: 5,
        text: "Absolutely breathtaking! The colors and movement bring Paris to life in a magical way.",
      },
      {
        name: "Lucas M.",
        date: "2025-09-16T21:00:00.000Z",
        rating: 5,
        text: "The brushstrokes make this painting feel so alive! A must-have for any Paris lover.",
      },
      {
        name: "Emma C.",
        date: "2025-09-17T21:00:00.000Z",
        rating: 4,
        text: "A beautiful piece! I love the detail in the Eiffel Tower, though I wish the foreground had a bit more contrast.",
      },
      {
        name: "Noah R.",
        date: "2025-09-18T21:00:00.000Z",
        rating: 5,
        text: "The way the light plays across the tower is stunning. It brings such elegance to my space!",
      },
      {
        name: "Sophia T.",
        date: "2025-09-19T21:00:00.000Z",
        rating: 5,
        text: "This painting captures everything I love about Paris—romance, beauty, and timeless charm!",
      },
    ],
  },
  {
    id: "c4d69e95-89bb-49f4-96be-0630a575f55a",
    title: "Eternal Venice",
    artist: "Alessandro Fiorini",
    image: {
      type: "landscape",
      width: 1792,
      height: 1024,
      uri: "/images/eternal_venice.webp",
    },
    description:
      "The enchanting canals of Venice come to life in this impressionist masterpiece. Gondolas drift through shimmering waters, reflecting the warm glow of lanterns and historic architecture. Expressive brushstrokes capture the romance and timeless charm of this breathtaking city, evoking a dreamlike atmosphere.",
    averageRating: 4.8,
    type: "landscape",
    sizes: [
      { width: 55, height: 40, price: 390 },
      { width: 70, height: 50, price: 500 },
      { width: 85, height: 60, price: 610 },
      { width: 100, height: 70, price: 720 },
      { width: 120, height: 85, price: 830 },
      { width: 140, height: 100, price: 940 },
    ],
    reviews: [
      {
        name: "Giulia M.",
        date: "2025-09-24T21:00:00.000Z",
        rating: 5,
        text: "This painting perfectly captures the magic of Venice! The water reflections are absolutely stunning.",
      },
      {
        name: "Leonardo P.",
        date: "2025-09-26T21:00:00.000Z",
        rating: 5,
        text: "I feel like I’m walking along the canals every time I look at this masterpiece. A truly remarkable piece!",
      },
      {
        name: "Clara B.",
        date: "2025-09-27T21:00:00.000Z",
        rating: 4,
        text: "Beautiful work! I love the colors, but I wish there was a bit more contrast in the sky.",
      },
      {
        name: "Marco D.",
        date: "2025-09-28T21:00:00.000Z",
        rating: 5,
        text: "The movement of the water is so well captured—it feels alive! A must-have for lovers of Venice.",
      },
      {
        name: "Sophia L.",
        date: "2025-09-29T21:00:00.000Z",
        rating: 5,
        text: "Absolutely mesmerizing! This painting brings the romance of Venice right into my home.",
      },
    ],
  },
  {
    id: "3916fef4-ecb3-4bd5-b8d3-0fa25aed0719",
    title: "Valley of Light",
    artist: "Matteo Lavigne",
    image: {
      type: "landscape",
      width: 1792,
      height: 1024,
      uri: "/images/valley_of_light.webp",
    },
    description:
      "Rolling green hills and distant mountains frame a serene valley, where a river winds gracefully through golden fields. Expressive impressionist brushstrokes capture the warmth of sunlight and the gentle movement of nature, evoking a sense of peace and untouched beauty.",
    averageRating: 4.8,
    type: "landscape",
    sizes: [
      { width: 55, height: 40, price: 380 },
      { width: 70, height: 50, price: 490 },
      { width: 85, height: 60, price: 600 },
      { width: 100, height: 70, price: 710 },
      { width: 120, height: 85, price: 820 },
      { width: 140, height: 100, price: 930 },
    ],
    reviews: [
      {
        name: "Amelia F.",
        date: "2025-10-04T21:00:00.000Z",
        rating: 5,
        text: "This painting brings such a sense of peace to my home! The brushstrokes make the valley feel so alive.",
      },
      {
        name: "Ethan R.",
        date: "2025-10-06T21:00:00.000Z",
        rating: 5,
        text: "A breathtaking piece! The way the sunlight plays over the hills is stunning.",
      },
      {
        name: "Olivia T.",
        date: "2025-10-07T21:00:00.000Z",
        rating: 4,
        text: "I love the colors, but I wish the river had a bit more detail. Still, an amazing piece!",
      },
      {
        name: "Daniel L.",
        date: "2025-10-08T21:00:00.000Z",
        rating: 5,
        text: "A perfect mix of depth and softness. It truly captures the beauty of untouched nature.",
      },
      {
        name: "Sophia N.",
        date: "2025-10-09T21:00:00.000Z",
        rating: 5,
        text: "This artwork makes me feel like I’m standing in the middle of a sunlit valley. Absolutely stunning!",
      },
    ],
  },
  {
    id: "1809aee7-d229-48ef-86de-4acbae15ba4f",
    title: "Sacred Heights of Tibet",
    artist: "Tenzing Norbu",
    image: {
      type: "landscape",
      width: 1792,
      height: 1024,
      uri: "/images/sacred_heights_of_tibet.webp",
    },
    description:
      "Snow-capped mountains tower over the vast Tibetan valleys, where a winding river reflects the golden hues of the sky. Vibrant monasteries and prayer flags bring a spiritual energy to the landscape, captured through expressive impressionist brushstrokes. A breathtaking tribute to Tibet’s serene and majestic beauty.",
    averageRating: 4.8,
    type: "landscape",
    sizes: [
      { width: 55, height: 40, price: 400 },
      { width: 70, height: 50, price: 510 },
      { width: 85, height: 60, price: 620 },
      { width: 100, height: 70, price: 730 },
      { width: 120, height: 85, price: 840 },
      { width: 140, height: 100, price: 950 },
    ],
    reviews: [
      {
        name: "Lobsang T.",
        date: "2025-10-14T21:00:00.000Z",
        rating: 5,
        text: "This painting perfectly captures the spirit of Tibet. The mountains feel alive with energy!",
      },
      {
        name: "Emily R.",
        date: "2025-10-16T21:00:00.000Z",
        rating: 5,
        text: "The brushstrokes create such a wonderful sense of movement. It’s a masterpiece!",
      },
      {
        name: "Nathan P.",
        date: "2025-10-17T21:00:00.000Z",
        rating: 4,
        text: "I love the monastery details, but I wish the river was a bit more defined. Still, an incredible work of art.",
      },
      {
        name: "Sophie D.",
        date: "2025-10-18T21:00:00.000Z",
        rating: 5,
        text: "A breathtaking scene! The use of light and shadow makes it feel so peaceful yet powerful.",
      },
      {
        name: "Noah K.",
        date: "2025-10-19T21:00:00.000Z",
        rating: 5,
        text: "This piece transports me to the heart of Tibet. The colors and depth are stunning!",
      },
    ],
  },
  {
    id: "0387325d-689e-42e6-baca-3aa303ad0555",
    title: "Eternal Peaks of the Himalayas",
    artist: "Surya Patel",
    image: {
      type: "square",
      width: 1024,
      height: 1024,
      uri: "/images/eternal_peaks_of_the_himalayas.webp",
    },
    description:
      "The majestic Himalayas rise into the sky, their snow-capped peaks bathed in golden light. Expressive impressionist brushstrokes bring the movement of clouds and icy slopes to life, evoking a breathtaking sense of tranquility and power. A timeless tribute to one of Earth’s most awe-inspiring landscapes.",
    averageRating: 4.8,
    type: "square",
    sizes: [
      { width: 40, height: 40, price: 410 },
      { width: 50, height: 50, price: 520 },
      { width: 60, height: 60, price: 630 },
      { width: 70, height: 70, price: 740 },
      { width: 85, height: 85, price: 850 },
      { width: 100, height: 100, price: 960 },
    ],
    reviews: [
      {
        name: "Kiran R.",
        date: "2025-10-24T21:00:00.000Z",
        rating: 5,
        text: "Absolutely breathtaking! The light on the peaks makes them feel alive.",
      },
      {
        name: "Elena M.",
        date: "2025-10-26T22:00:00.000Z",
        rating: 5,
        text: "The depth and brushwork are phenomenal. It feels like I’m staring at the Himalayas from my window!",
      },
      {
        name: "Daniel K.",
        date: "2025-10-27T22:00:00.000Z",
        rating: 4,
        text: "The sky is mesmerizing, but I wish there was a bit more shadow detail on the slopes. Still a masterpiece!",
      },
      {
        name: "Sophia P.",
        date: "2025-10-28T22:00:00.000Z",
        rating: 5,
        text: "The impressionist style makes this landscape feel magical and dreamlike. I love it!",
      },
      {
        name: "Noah T.",
        date: "2025-10-29T22:00:00.000Z",
        rating: 5,
        text: "This painting captures the pure grandeur of the Himalayas. An absolute must-have for mountain lovers.",
      },
    ],
  },
  {
    id: "e2a3f354-2586-4d5f-860d-4432cdb94c2b",
    title: "Tranquil Shoreline",
    artist: "Emilia Laurent",
    image: {
      type: "landscape",
      width: 1792,
      height: 1024,
      uri: "/images/tranquil_shoreline.webp",
    },
    description:
      "Golden sands stretch along the shoreline as gentle turquoise waves roll onto the beach. Expressive impressionist brushstrokes bring movement to the water and sky, creating a soft, dreamy atmosphere. A peaceful and evocative tribute to the serenity of the sea.",
    averageRating: 4.8,
    type: "landscape",
    sizes: [
      { width: 55, height: 40, price: 380 },
      { width: 70, height: 50, price: 490 },
      { width: 85, height: 60, price: 600 },
      { width: 100, height: 70, price: 710 },
      { width: 120, height: 85, price: 820 },
      { width: 140, height: 100, price: 930 },
    ],
    reviews: [
      {
        name: "Olivia H.",
        date: "2025-11-04T22:00:00.000Z",
        rating: 5,
        text: "Looking at this painting makes me feel like I’m on a beach getaway. The colors are so soothing!",
      },
      {
        name: "Daniel R.",
        date: "2025-11-06T22:00:00.000Z",
        rating: 5,
        text: "The brushstrokes perfectly capture the movement of the waves. A stunning piece!",
      },
      {
        name: "Sophia L.",
        date: "2025-11-07T22:00:00.000Z",
        rating: 4,
        text: "A beautiful painting! I just wish the sand had a little more texture, but otherwise perfect.",
      },
      {
        name: "Ethan M.",
        date: "2025-11-08T22:00:00.000Z",
        rating: 5,
        text: "I can almost hear the waves crashing. The impressionist style adds such a dreamy feel.",
      },
      {
        name: "Charlotte T.",
        date: "2025-11-09T22:00:00.000Z",
        rating: 5,
        text: "This is exactly what I needed for my beach house. It’s peaceful, bright, and absolutely gorgeous!",
      },
    ],
  },
  {
    id: "51047f0e-2235-446b-863f-1da3fa79aca7",
    title: "Tempest in the Sky",
    artist: "Elias Varnen",
    image: {
      type: "landscape",
      width: 1792,
      height: 1024,
      uri: "/images/tempest_in_the_sky.webp",
    },
    description:
      "Dark storm clouds swirl in a dramatic dance of blues and grays, illuminated by brilliant flashes of lightning. Expressive impressionist brushstrokes bring the movement of the storm to life, blending power and beauty in a breathtaking composition. A stunning portrayal of nature’s raw energy.",
    averageRating: 4.8,
    type: "landscape",
    sizes: [
      { width: 55, height: 40, price: 390 },
      { width: 70, height: 50, price: 500 },
      { width: 85, height: 60, price: 610 },
      { width: 100, height: 70, price: 720 },
      { width: 120, height: 85, price: 830 },
      { width: 140, height: 100, price: 940 },
    ],
    reviews: [
      {
        name: "Alexander M.",
        date: "2025-11-14T22:00:00.000Z",
        rating: 5,
        text: "The energy in this painting is incredible! It really captures the power of a storm.",
      },
      {
        name: "Sophia W.",
        date: "2025-11-16T22:00:00.000Z",
        rating: 5,
        text: "The lightning and movement of the clouds are mesmerizing. Such a dramatic and stunning piece!",
      },
      {
        name: "Ethan K.",
        date: "2025-11-17T22:00:00.000Z",
        rating: 4,
        text: "A breathtaking composition. I only wish the contrast in the clouds was a little stronger.",
      },
      {
        name: "Liam T.",
        date: "2025-11-18T22:00:00.000Z",
        rating: 5,
        text: "This artwork makes me feel like I’m standing right under the storm. It’s so vivid and intense!",
      },
      {
        name: "Charlotte P.",
        date: "2025-11-19T22:00:00.000Z",
        rating: 5,
        text: "Absolutely electrifying! This is the perfect statement piece for my living room.",
      },
    ],
  },
];

export default artworks;
